% =============================================================================
% FILE: models/differential_thrust_roll_sim.m
% PROJECT: RUPAK VTVL GNC Architecture
% AUTHOR: GNC Engineering Team
% MATLAB: R2024a
% =============================================================================
%
% PURPOSE:
%   Simulates roll-axis attitude control for the RUPAK 28m, 9-engine VTVL
%   rocket using Incremental Nonlinear Dynamic Inversion (INDI). Roll torque
%   is generated by differentially modulating the RPM of opposing peripheral
%   Shakti electric-pump-fed engines. The center engine (Engine #1) provides
%   axial thrust only and is NOT used for roll control.
%
% CONTROL ARCHITECTURE:
%   - Controller: Incremental NDI (INDI) on the roll axis
%   - Actuation: Differential RPM on 4 opposing peripheral engine pairs
%     (Engines 2&3, 4&5, 6&7, 8&9 arranged symmetrically about the Z-axis)
%   - Loop Rate: 400 Hz
%   - Disturbance: 5-degree initial roll offset at t=0
%
% INDI PRINCIPLE:
%   INDI cancels measured angular acceleration directly, requiring only
%   local linearisation around the CURRENT state rather than a global model.
%   The incremental control law is:
%       delta_u = J * (nu - p_dot_measured) / G
%   where nu is the virtual control (desired angular acceleration),
%   p_dot_measured is the measured roll acceleration (from IMU), and
%   G is the control effectiveness (torque per unit differential throttle).
%
% ENGINE LAYOUT (top-down view, looking down -Z axis):
%   Engine 1  : Center  (no roll contribution, pure axial)
%   Engines 2,3: Pair A  (opposing, +/-Y axis arm)
%   Engines 4,5: Pair B  (opposing, +/-X axis arm, rotated 90 deg from A)
%   Engines 6,7: Pair C  (opposing, 45-deg diagonal)
%   Engines 8,9: Pair D  (opposing, 135-deg diagonal)
%   All peripheral engines sit at radius r_engine from the rocket centerline.
%
% REFERENCES:
%   [1] Sieberling, S. et al., "Robust Flight Control Using INDI," AIAA 2010
%   [2] Smeur, E. et al., "Adaptive Incremental NDI for Multirotor," JGCD 2016
%   [3] RUPAK GNC Architecture Document, Section 4.2 (Roll Channel)
%
% =============================================================================

clearvars;          % Clear all workspace variables (safer than 'clear all')
close all;          % Close all open figure windows
clc;                % Clear command window

fprintf('=============================================================\n');
fprintf('  RUPAK GNC | Differential Thrust Roll Control (INDI)\n');
fprintf('  Simulation initialising...\n');
fprintf('=============================================================\n\n');

% =============================================================================
% SECTION 1: SIMULATION PARAMETERS
% =============================================================================

% --- Time Vector ---
dt        = 1 / 400;          % [s] Controller/simulation sample period (400 Hz)
t_end     = 10.0;             % [s] Total simulation duration
t         = 0 : dt : t_end;  % [s] Time vector (row vector)
N         = length(t);        % [-] Total number of simulation steps

fprintf('Simulation time: %.1f s | Sample rate: %d Hz | Steps: %d\n', ...
        t_end, round(1/dt), N);

% =============================================================================
% SECTION 2: VEHICLE PHYSICAL PARAMETERS
% =============================================================================

% --- Rotational Inertia ---
J_roll    = 85000;            % [kg·m²] Roll-axis moment of inertia (RUPAK full-stack)

% --- Engine Geometry ---
r_engine  = 1.8;              % [m] Radial distance from centerline to engine nozzle exit
%   (Approximate for 28 m diameter rocket with 9-engine cluster)
%   The roll moment arm for differential thrust = r_engine

% --- Shakti Engine Parameters ---
% Nominal operating condition (baseline throttle level)
RPM_nom       = 18000;        % [RPM] Nominal electric pump motor speed at 100% throttle
RPM_max       = RPM_nom;      % [RPM] Maximum allowable pump speed
RPM_min       = RPM_nom * 0.60; % [RPM] Minimum allowable pump speed (60% - flame-out limit)

% Throttle-to-thrust sensitivity
% At nominal RPM, each Shakti engine produces ~850 kN thrust (full throttle)
F_nom_per_engine = 850e3;     % [N] Nominal thrust per engine at 100% throttle

% Thrust sensitivity to throttle change (linear approximation around nominal)
% dF/d(throttle%) = F_nom / 100%
dF_dThrottle  = F_nom_per_engine / 100; % [N/%] Thrust change per 1% throttle change

% --- Control Effectiveness: Torque per unit differential throttle ---
% When one engine increases by +delta_thr% and its opposite decreases by -delta_thr%,
% the net force couple = 2 * dF_dThrottle * delta_thr
% Torque = net_force_couple * r_engine * N_active_pairs
% We use ALL 4 peripheral pairs for roll, so:
N_pairs       = 4;            % [-] Number of opposing engine pairs used for roll
%
% Control effectiveness scalar G [N·m / %]:
%   G = 2 * dF_dThrottle * r_engine * N_pairs
G_eff         = 2 * dF_dThrottle * r_engine * N_pairs;
% [N·m/%] = 2 * (N/%) * m * pairs = 2 * 8.5e6 * 1.8 * 4

fprintf('\nVehicle Parameters:\n');
fprintf('  J_roll        = %.0f kg·m²\n', J_roll);
fprintf('  r_engine      = %.2f m\n', r_engine);
fprintf('  RPM_nom       = %.0f RPM\n', RPM_nom);
fprintf('  F_nom/engine  = %.0f kN\n', F_nom_per_engine/1e3);
fprintf('  G_eff         = %.4e N·m per %%throttle\n', G_eff);

% =============================================================================
% SECTION 3: INDI CONTROLLER PARAMETERS
% =============================================================================

% --- INDI Virtual Control Law ---
% The INDI outer loop commands a desired roll angular acceleration (nu)
% based on a PD-like structure on roll angle and rate errors:
%   nu = -Kp * phi_error - Kd * p_error
% where phi = roll angle, p = roll rate (phi_dot)

% Proportional gain on roll angle error [rad/s² per rad]
% Design target: ~3.2 s settling. For a 2nd-order system:
%   omega_n ~ 4 / (zeta * T_s) with zeta=0.7, T_s=3.2 s => omega_n ~ 1.79 rad/s
omega_n       = 1.79;         % [rad/s] Natural frequency target
zeta          = 0.70;         % [-] Damping ratio (slightly underdamped, fast response)

% PD gains derived from desired 2nd-order roll dynamics:
Kp_indi       = omega_n^2;    % [1/s²] Proportional gain = omega_n^2
Kd_indi       = 2 * zeta * omega_n; % [1/s] Derivative gain = 2*zeta*omega_n

fprintf('\nINDI Controller Gains:\n');
fprintf('  omega_n       = %.4f rad/s\n', omega_n);
fprintf('  zeta          = %.2f\n', zeta);
fprintf('  Kp_indi       = %.4f 1/s²\n', Kp_indi);
fprintf('  Kd_indi       = %.4f 1/s\n', Kd_indi);

% --- Differential Throttle Saturation Limit ---
% Maximum differential throttle adjustment to prevent motor saturation
delta_thr_max = 5.0;          % [%] +/- saturation limit (requirement from spec)
delta_thr_min = -delta_thr_max;

% --- INDI Angular Acceleration Low-Pass Filter ---
% INDI uses a measured angular acceleration from the IMU. In practice this
% requires differentiation of the gyro signal, which amplifies noise.
% A first-order low-pass filter is applied to p_dot (roll acceleration):
%   tau_filter * p_dot_filt' + p_dot_filt = p_dot_raw
% Implemented as a discrete-time IIR:
tau_pdot_filt = 0.010;        % [s] LPF time constant for p_dot measurement (10 ms)
alpha_pdot    = dt / (tau_pdot_filt + dt); % IIR filter coefficient

% --- RPM Command Low-Pass Filter (actuator smoothing) ---
tau_rpm_filt  = 0.020;        % [s] Smoothing filter for RPM commands (20 ms)
alpha_rpm     = dt / (tau_rpm_filt + dt);

% =============================================================================
% SECTION 4: INITIAL CONDITIONS AND DISTURBANCE
% =============================================================================

% Roll angle initial condition (5 degree disturbance at t=0)
phi0_deg      = 5.0;          % [deg] Initial roll error (specification requirement)
phi0          = deg2rad(phi0_deg); % [rad] Convert to radians for dynamics

% Roll rate initial condition (vehicle is stationary at t=0)
p0            = 0.0;          % [rad/s] Initial roll rate

% Roll setpoint (desired roll angle = 0 for nominal upright flight)
phi_ref       = 0.0;          % [rad] Roll angle reference (wings-level)
p_ref         = 0.0;          % [rad/s] Roll rate reference

fprintf('\nInitial Conditions:\n');
fprintf('  phi(0) = %.1f deg | p(0) = %.4f rad/s\n', phi0_deg, p0);
fprintf('  phi_ref = %.1f deg (wings-level)\n', rad2deg(phi_ref));

% =============================================================================
% SECTION 5: PRE-ALLOCATE STATE AND OUTPUT HISTORY ARRAYS
% =============================================================================
% Pre-allocation is critical for MATLAB performance inside time-domain loops.
% Each array stores the time history of one signal.

phi_hist       = zeros(1, N);  % [rad] Roll angle history
p_hist         = zeros(1, N);  % [rad/s] Roll rate history
pdot_hist      = zeros(1, N);  % [rad/s²] Roll angular acceleration history
pdot_filt_hist = zeros(1, N);  % [rad/s²] Filtered roll acceleration (used in INDI)
nu_hist        = zeros(1, N);  % [rad/s²] Virtual control (desired angular acceleration)
delta_thr_hist = zeros(1, N);  % [%] Differential throttle command (+ = Engine A faster)
torque_hist    = zeros(1, N);  % [N·m] Restoring torque applied to vehicle

% Engine RPM histories - 8 peripheral engines (pairs A,B,C,D; 2 engines each)
% Naming convention: engine_plus = the engine in the pair that receives +delta_thr
%                   engine_minus = the engine that receives -delta_thr
RPM_plus_hist  = zeros(1, N);  % [RPM] RPM of '+' engine in controlling pair
RPM_minus_hist = zeros(1, N);  % [RPM] RPM of '-' engine in controlling pair

% =============================================================================
% SECTION 6: INITIALISE STATE VARIABLES
% =============================================================================

% Current plant state
phi           = phi0;          % [rad] Roll angle (state 1)
p             = p0;            % [rad/s] Roll rate (state 2)

% Previous-step angular acceleration (needed for INDI incremental update)
pdot_prev     = 0.0;           % [rad/s²] p_dot at previous sample (init to 0)
pdot_filt     = 0.0;           % [rad/s²] Filtered p_dot (LPF output, init to 0)

% Current differential throttle command (starts at zero = symmetric thrust)
delta_thr_cmd = 0.0;           % [%] Differential throttle command

% Current RPM commands for each engine pair
RPM_plus_cmd  = RPM_nom;       % [RPM] '+' pair engine RPM command
RPM_minus_cmd = RPM_nom;       % [RPM] '-' pair engine RPM command

% =============================================================================
% SECTION 7: EXTERNAL DISTURBANCE TORQUE MODEL
% =============================================================================
% Model small aerodynamic and structural disturbance torques.
% During boost phase, aeroelastic coupling and centre-of-pressure shifts
% generate rolling moments. Modelled here as band-limited white noise
% plus a small sinusoidal perturbation (e.g., from sloshing).

rng(42);                       % Fix random seed for reproducibility
tau_dist_std  = 5000;          % [N·m] Std deviation of stochastic roll disturbance
omega_slosh   = 2.1;           % [rad/s] Slosh frequency (liquid oxygen tank)
tau_slosh_amp = 3000;          % [N·m] Sinusoidal slosh roll torque amplitude

% Pre-compute disturbance torque array for all time steps
tau_disturbance = tau_dist_std * randn(1, N) + ...
                  tau_slosh_amp * sin(omega_slosh * t);

fprintf('\nDisturbance Model:\n');
fprintf('  Stochastic noise: sigma = %.0f N·m\n', tau_dist_std);
fprintf('  Slosh torque: %.0f N·m @ %.2f rad/s\n', tau_slosh_amp, omega_slosh);

% =============================================================================
% SECTION 8: MAIN SIMULATION LOOP (400 Hz INDI Control)
% =============================================================================

fprintf('\nRunning simulation...\n');

for k = 1 : N
    % ------------------------------------------------------------------
    % 8.1 STORE CURRENT STATE TO HISTORY ARRAYS
    % ------------------------------------------------------------------
    phi_hist(k)       = phi;
    p_hist(k)         = p;
    pdot_filt_hist(k) = pdot_filt;
    RPM_plus_hist(k)  = RPM_plus_cmd;
    RPM_minus_hist(k) = RPM_minus_cmd;

    % ------------------------------------------------------------------
    % 8.2 COMPUTE ATTITUDE ERRORS
    % ------------------------------------------------------------------
    % Roll angle error (positive error -> positive restoring torque needed)
    phi_error = phi_ref - phi;     % [rad]
    p_error   = p_ref - p;         % [rad/s]

    % ------------------------------------------------------------------
    % 8.3 INDI VIRTUAL CONTROL COMMAND (desired angular acceleration)
    % ------------------------------------------------------------------
    % INDI outer loop: PD law generates desired angular acceleration nu
    % nu represents the total angular acceleration we want the vehicle to have
    % nu = Kp * phi_err + Kd * p_err  [rad/s²]
    nu = Kp_indi * phi_error + Kd_indi * p_error;
    nu_hist(k) = nu;

    % ------------------------------------------------------------------
    % 8.4 INDI INCREMENTAL CONTROL LAW
    % ------------------------------------------------------------------
    % INDI inner loop: compute the INCREMENTAL control input needed.
    % Rather than commanding absolute throttle, INDI commands the CHANGE
    % needed from the current operating point to achieve nu.
    %
    % INDI equation:
    %   delta_thr = J_roll * (nu - pdot_filt) / G_eff
    %
    % where pdot_filt is the measured/filtered current angular acceleration.
    % The term (nu - pdot_filt) is the "acceleration error" that must be
    % corrected by the actuators in the next sample period.
    %
    % Units check:
    %   [kg·m²] * [rad/s²] / [N·m/%] = [kg·m²·rad/s²] / [kg·m²/s²·%]
    %                                 = [%]  ✓

    delta_thr_raw = J_roll * (nu - pdot_filt) / G_eff;   % [%] unconstrained

    % ------------------------------------------------------------------
    % 8.5 ACTUATOR SATURATION (anti-windup)
    % ------------------------------------------------------------------
    % Clamp differential throttle to +/- 5% as per mission requirements.
    % This prevents motor saturation and maintains linearity assumption.
    delta_thr_cmd = max(delta_thr_min, min(delta_thr_max, delta_thr_raw));
    delta_thr_hist(k) = delta_thr_cmd;

    % ------------------------------------------------------------------
    % 8.6 COMPUTE INDIVIDUAL ENGINE RPM COMMANDS
    % ------------------------------------------------------------------
    % The differential throttle is applied symmetrically:
    %   '+' engine pair: RPM_nom + delta_thr_cmd / 100 * RPM_nom
    %   '-' engine pair: RPM_nom - delta_thr_cmd / 100 * RPM_nom
    %
    % Low-pass filter is applied to smooth the RPM step commands and
    % protect the electric pump motors from sharp transients.

    % Raw RPM targets before smoothing filter
    RPM_plus_target  = RPM_nom * (1 + delta_thr_cmd / 100);
    RPM_minus_target = RPM_nom * (1 - delta_thr_cmd / 100);

    % Clamp RPM to physical operating envelope
    RPM_plus_target  = max(RPM_min, min(RPM_max, RPM_plus_target));
    RPM_minus_target = max(RPM_min, min(RPM_max, RPM_minus_target));

    % Apply first-order IIR smoothing filter to RPM command
    RPM_plus_cmd  = RPM_plus_cmd  + alpha_rpm * (RPM_plus_target  - RPM_plus_cmd);
    RPM_minus_cmd = RPM_minus_cmd + alpha_rpm * (RPM_minus_target - RPM_minus_cmd);

    % ------------------------------------------------------------------
    % 8.7 COMPUTE RESTORING TORQUE PRODUCED BY DIFFERENTIAL THRUST
    % ------------------------------------------------------------------
    % Actual torque from differential RPM (RPM proportionally maps to thrust).
    % Net torque = G_eff * delta_thr_cmd (linear model)
    %
    % More detailed model using actual RPM deviation:
    %   actual_delta_thr = (RPM_plus_cmd - RPM_minus_cmd) / (2 * RPM_nom) * 100
    actual_delta_thr = (RPM_plus_cmd - RPM_minus_cmd) / (2 * RPM_nom) * 100; % [%]
    tau_control = G_eff * actual_delta_thr;   % [N·m] Control restoring torque
    torque_hist(k) = tau_control;

    % ------------------------------------------------------------------
    % 8.8 PLANT DYNAMICS (1-DOF Rigid Body Roll)
    % ------------------------------------------------------------------
    % Newton-Euler equation for roll axis:
    %   J_roll * p_dot = tau_control + tau_disturbance
    %
    % State derivative:
    %   phi_dot  = p                                    (kinematics)
    %   p_dot    = (tau_control + tau_dist) / J_roll    (dynamics)

    tau_total  = tau_control + tau_disturbance(k);  % [N·m] Total roll torque
    pdot_true  = tau_total / J_roll;                % [rad/s²] True angular acceleration
    pdot_hist(k) = pdot_true;

    % ------------------------------------------------------------------
    % 8.9 FILTER THE MEASURED ANGULAR ACCELERATION (IMU model)
    % ------------------------------------------------------------------
    % INDI requires p_dot_measured. In hardware, this comes from the IMU
    % gyro differentiator + LPF. We add a small noise term here.
    pdot_measured = pdot_true + 0.005 * randn; % [rad/s²] Noise from IMU

    % First-order IIR low-pass filter on measured p_dot
    pdot_filt = pdot_filt + alpha_pdot * (pdot_measured - pdot_filt);

    % ------------------------------------------------------------------
    % 8.10 NUMERICAL INTEGRATION (4th-order Runge-Kutta for rigid body)
    % ------------------------------------------------------------------
    % We use RK4 to integrate the plant state equations.
    % The torque applied to the plant at this step is tau_control + tau_dist(k).
    % We treat tau_total as constant over the sub-steps (ZOH assumption).
    %
    % State vector X = [phi; p]
    % X_dot = f(X) = [p; tau_total / J_roll]

    % RK4 slope k1
    k1_phi = p;
    k1_p   = tau_total / J_roll;

    % RK4 slope k2 (mid-step using k1)
    phi_mid1 = phi + 0.5 * dt * k1_phi;
    p_mid1   = p   + 0.5 * dt * k1_p;
    k2_phi   = p_mid1;
    k2_p     = tau_total / J_roll;    % Torque constant over step (ZOH)

    % RK4 slope k3 (mid-step using k2)
    phi_mid2 = phi + 0.5 * dt * k2_phi;
    p_mid2   = p   + 0.5 * dt * k2_p;
    k3_phi   = p_mid2;
    k3_p     = tau_total / J_roll;

    % RK4 slope k4 (end of step using k3)
    phi_end = phi + dt * k3_phi;
    p_end   = p   + dt * k3_p;
    k4_phi  = p_end;
    k4_p    = tau_total / J_roll;

    % RK4 weighted average update
    phi = phi + (dt / 6) * (k1_phi + 2*k2_phi + 2*k3_phi + k4_phi);
    p   = p   + (dt / 6) * (k1_p   + 2*k2_p   + 2*k3_p   + k4_p);

end

fprintf('Simulation complete.\n\n');

% =============================================================================
% SECTION 9: POST-PROCESSING AND METRICS
% =============================================================================

% Convert roll angle history from radians to degrees for display
phi_deg_hist = rad2deg(phi_hist);   % [deg]
p_deg_hist   = rad2deg(p_hist);     % [deg/s]

% Compute settling time: first time |phi| < 2% of initial error (0.1 deg)
settling_threshold = 0.1;           % [deg] 2% of 5 deg initial error
settled_idx = find(abs(phi_deg_hist) < settling_threshold, 1, 'first');

if ~isempty(settled_idx)
    T_settle = t(settled_idx);
    fprintf('Settling time (|phi| < %.2f deg): %.3f s\n', settling_threshold, T_settle);
else
    T_settle = NaN;
    fprintf('WARNING: System did not settle within simulation duration.\n');
end

% Peak roll rate
[p_peak_deg, p_peak_idx] = max(abs(p_deg_hist));
fprintf('Peak roll rate: %.4f deg/s at t = %.4f s\n', p_peak_deg, t(p_peak_idx));

% Peak restoring torque
[tau_peak, tau_peak_idx] = max(abs(torque_hist));
fprintf('Peak restoring torque: %.1f N·m at t = %.4f s\n', tau_peak, t(tau_peak_idx));

% Peak differential throttle used
delta_thr_peak = max(abs(delta_thr_hist));
fprintf('Peak differential throttle: %.4f %%\n', delta_thr_peak);

% =============================================================================
% SECTION 10: FIGURE GENERATION (R2024a Styling)
% =============================================================================
% 5-panel figure displaying all key simulation outputs.
% Using R2024a default colororder and graphics defaults.

fprintf('\nGenerating 5-panel figure...\n');

fig1 = figure('Name', 'RUPAK Roll Control - INDI Simulation', ...
              'NumberTitle', 'off', ...
              'Color', [0.15 0.15 0.18], ...
              'Units', 'normalized', ...
              'OuterPosition', [0.02 0.02 0.96 0.96]);

% Set R2024a default color palette for axes
clr_bg   = [0.15 0.15 0.18];   % Dark background
clr_ax   = [0.22 0.22 0.26];   % Slightly lighter axis background
clr_grid = [0.35 0.35 0.40];   % Grid line color
clr_txt  = [0.92 0.92 0.92];   % Text color (near-white)
clr_blue = [0.25 0.60 0.95];   % Primary signal color
clr_orng = [0.98 0.62 0.12];   % Secondary signal color
clr_grn  = [0.28 0.87 0.55];   % Tertiary signal color
clr_red  = [0.95 0.30 0.28];   % Alert/saturation color
clr_prpl = [0.72 0.40 0.95];   % Quaternary color

% Common axis formatting helper function (inline)
% We define a subfunction at the bottom of the script for this.

% ---------------------------------------------------------------------------
% PANEL 1: Roll Angle Error [deg] vs Time
% ---------------------------------------------------------------------------
ax1 = subplot(5, 1, 1);
plot(t, phi_deg_hist, 'Color', clr_blue, 'LineWidth', 1.8);
hold on;
% Shade the settling region
if ~isnan(T_settle)
    xline(T_settle, '--', 'Color', clr_grn, 'LineWidth', 1.2, ...
          'Label', sprintf('T_{settle} = %.2f s', T_settle), ...
          'LabelHorizontalAlignment', 'right', ...
          'LabelVerticalAlignment', 'bottom', ...
          'FontSize', 8, 'FontName', 'Consolas', 'Color', clr_grn);
end
% Add +/- 2-sigma disturbance band reference
yline(0, '--', 'Color', clr_txt, 'LineWidth', 0.8, 'Alpha', 0.4);
yline( settling_threshold, ':', 'Color', clr_grn, 'LineWidth', 0.9, 'Alpha', 0.7);
yline(-settling_threshold, ':', 'Color', clr_grn, 'LineWidth', 0.9, 'Alpha', 0.7);
hold off;
ylabel('\phi_{err} (deg)', 'Color', clr_txt, 'FontName', 'Consolas', 'FontSize', 9);
title({'RUPAK VTVL | INDI Differential Thrust Roll Control'; ...
       sprintf('J_{roll} = %.0f kg·m²  |  \\phi_0 = %.0f°  |  400 Hz  |  10 s', ...
               J_roll, phi0_deg)}, ...
       'Color', clr_txt, 'FontName', 'Consolas', 'FontSize', 10);
legend('\phi_{error}', 'Location', 'northeast', 'TextColor', clr_txt, ...
       'Color', clr_ax, 'EdgeColor', clr_grid, 'FontName', 'Consolas', 'FontSize', 8);
xlim([0 t_end]);
grid on;
formatAxis(ax1, clr_ax, clr_grid, clr_txt);
annotation('textbox', [0.88 0.885 0.12 0.04], ...
           'String', sprintf('T_s \\approx %.2f s', T_settle), ...
           'Color', clr_grn, 'BackgroundColor', clr_ax, 'EdgeColor', clr_grid, ...
           'FontName', 'Consolas', 'FontSize', 8, 'FitBoxToText', 'on');

% ---------------------------------------------------------------------------
% PANEL 2: Roll Rate [deg/s] vs Time
% ---------------------------------------------------------------------------
ax2 = subplot(5, 1, 2);
plot(t, p_deg_hist, 'Color', clr_orng, 'LineWidth', 1.8);
hold on;
yline(0, '--', 'Color', clr_txt, 'LineWidth', 0.8, 'Alpha', 0.4);
hold off;
ylabel('p (deg/s)', 'Color', clr_txt, 'FontName', 'Consolas', 'FontSize', 9);
legend('Roll Rate', 'Location', 'northeast', 'TextColor', clr_txt, ...
       'Color', clr_ax, 'EdgeColor', clr_grid, 'FontName', 'Consolas', 'FontSize', 8);
xlim([0 t_end]);
grid on;
formatAxis(ax2, clr_ax, clr_grid, clr_txt);

% ---------------------------------------------------------------------------
% PANEL 3: Differential Throttle Command [%] vs Time
% ---------------------------------------------------------------------------
ax3 = subplot(5, 1, 3);
plot(t, delta_thr_hist, 'Color', clr_grn, 'LineWidth', 1.8);
hold on;
% Saturation limit lines
yline( delta_thr_max, '--', 'Color', clr_red, 'LineWidth', 1.0, ...
       'Label', '+5% Sat.', 'LabelHorizontalAlignment', 'left', ...
       'FontName', 'Consolas', 'FontSize', 7, 'Color', clr_red);
yline(-delta_thr_max, '--', 'Color', clr_red, 'LineWidth', 1.0, ...
       'Label', '-5% Sat.', 'LabelHorizontalAlignment', 'left', ...
       'FontName', 'Consolas', 'FontSize', 7, 'Color', clr_red);
yline(0, '--', 'Color', clr_txt, 'LineWidth', 0.8, 'Alpha', 0.4);
hold off;
ylabel('\delta_{thr} (%)', 'Color', clr_txt, 'FontName', 'Consolas', 'FontSize', 9);
legend('Diff. Throttle', 'Location', 'northeast', 'TextColor', clr_txt, ...
       'Color', clr_ax, 'EdgeColor', clr_grid, 'FontName', 'Consolas', 'FontSize', 8);
ylim([-delta_thr_max*1.4  delta_thr_max*1.4]);
xlim([0 t_end]);
grid on;
formatAxis(ax3, clr_ax, clr_grid, clr_txt);

% ---------------------------------------------------------------------------
% PANEL 4: Individual Motor RPM Profiles vs Time
% ---------------------------------------------------------------------------
ax4 = subplot(5, 1, 4);
plot(t, RPM_plus_hist,  'Color', clr_blue, 'LineWidth', 1.6);
hold on;
plot(t, RPM_minus_hist, 'Color', clr_red,  'LineWidth', 1.6);
yline(RPM_nom, '--', 'Color', clr_txt, 'LineWidth', 0.8, 'Alpha', 0.5, ...
      'Label', 'RPM_{nom}', 'LabelHorizontalAlignment', 'left', ...
      'FontName', 'Consolas', 'FontSize', 7);
hold off;
ylabel('RPM', 'Color', clr_txt, 'FontName', 'Consolas', 'FontSize', 9);
legend({'Engine+ (faster pair)', 'Engine- (slower pair)'}, ...
       'Location', 'northeast', 'TextColor', clr_txt, 'Color', clr_ax, ...
       'EdgeColor', clr_grid, 'FontName', 'Consolas', 'FontSize', 8);
ylim([RPM_nom * 0.90  RPM_nom * 1.10]);
xlim([0 t_end]);
grid on;
formatAxis(ax4, clr_ax, clr_grid, clr_txt);

% ---------------------------------------------------------------------------
% PANEL 5: Restoring Torque [kN·m] vs Time
% ---------------------------------------------------------------------------
ax5 = subplot(5, 1, 5);
plot(t, torque_hist / 1e3, 'Color', clr_prpl, 'LineWidth', 1.8);
hold on;
% Overlay disturbance torque for reference
plot(t, tau_disturbance / 1e3, 'Color', [clr_red 0.3], 'LineWidth', 0.8);
yline(0, '--', 'Color', clr_txt, 'LineWidth', 0.8, 'Alpha', 0.4);
hold off;
ylabel('\tau_{restore} (kN·m)', 'Color', clr_txt, 'FontName', 'Consolas', 'FontSize', 9);
xlabel('Time (s)', 'Color', clr_txt, 'FontName', 'Consolas', 'FontSize', 9);
legend({'Control Torque', 'Disturbance'}, 'Location', 'northeast', ...
       'TextColor', clr_txt, 'Color', clr_ax, 'EdgeColor', clr_grid, ...
       'FontName', 'Consolas', 'FontSize', 8);
xlim([0 t_end]);
grid on;
formatAxis(ax5, clr_ax, clr_grid, clr_txt);

% Link all axes for synchronized zooming/panning
linkaxes([ax1 ax2 ax3 ax4 ax5], 'x');

% Overall figure annotation with RUPAK branding
annotation('textbox', [0.0 0.0 0.30 0.025], ...
           'String', 'RUPAK VTVL | GNC Architecture | INDI Roll Control @ 400 Hz', ...
           'Color', [clr_txt 0.6], 'BackgroundColor', 'none', 'EdgeColor', 'none', ...
           'FontName', 'Consolas', 'FontSize', 7, 'FitBoxToText', 'off');

fprintf('Figure 1 generated: 5-panel INDI Roll Control results.\n');
fprintf('\n--- Simulation Summary ---\n');
fprintf('  Settling time   : %.3f s (spec: ~3.2 s)\n', T_settle);
fprintf('  Peak roll rate  : %.4f deg/s\n', p_peak_deg);
fprintf('  Peak diff thr   : %.4f %% (limit: +/-%.1f %%)\n', delta_thr_peak, delta_thr_max);
fprintf('  Peak torque     : %.2f kN·m\n', tau_peak / 1e3);
fprintf('===========================================================\n');

% =============================================================================
% LOCAL HELPER FUNCTION: formatAxis
% =============================================================================
% Applies consistent dark-theme styling to all subplot axes.
% Must be defined as a local function (valid in R2016b+).

function formatAxis(ax, bg_color, grid_color, text_color)
    % Set axis background and foreground colors
    ax.Color            = bg_color;
    ax.XColor           = text_color;
    ax.YColor           = text_color;
    ax.GridColor        = grid_color;
    ax.MinorGridColor   = grid_color;
    ax.GridAlpha        = 0.5;
    ax.MinorGridAlpha   = 0.3;
    ax.FontName         = 'Consolas';
    ax.FontSize         = 8;
    ax.LineWidth        = 0.8;
    ax.Box              = 'on';
    ax.XMinorGrid       = 'on';
    ax.YMinorGrid       = 'on';
    ax.TickDir          = 'out';
    ax.TickLength       = [0.008 0.010];
end

% =============================================================================
% END OF FILE: differential_thrust_roll_sim.m
% =============================================================================
